Various improvements for usage with jupyter notebooks
eos/eos pull request #284
Opened 2021-03-07 16:45 UTC by pluegh

2021-03-07 17:19 UTC, pluegh commented
The tests fail:
```
Traceback (most recent call last):
  File "/usr/bin/eos-analysis", line 487, in <module>
    main()
  File "/usr/bin/eos-analysis", line 259, in main
    args.cmd(args)
  File "/usr/bin/eos-analysis", line 391, in cmd_sample_mcmc
    samples, weights = analysis.sample(N=args.N, stride=args.stride, pre_N=args.pre_N, preruns=args.preruns, rng=rng)
  File "/usr/lib/python3.6/dist-packages/eos/analysis.py", line 283, in sample
    for i in progressbar(range(0, preruns), desc="Pre-runs", leave=False):
TypeError: <lambda>() got an unexpected keyword argument 'desc'
```

Dammit, I did not test this outside of jupyter, where the progress bar skipped. Fix will be on the way.

2021-03-09 12:03 UTC, dvandyk requested changes
Thank you very much @pluegh!

Changes requested:

1. For the weights, throw an appropriate error if both ``data['weights']`` and ``data['log_weights']`` are provided.
2. For the progress bar, please amend the commit message regarding vanishing progress bars.

2021-03-09 12:03 UTC, dvandyk commented on python/eos/analysis.py
> +        for step in progressbar(range(steps), desc="Adaptions", leave=False):
Ditto, see above.

2021-03-09 13:58 UTC, dvandyk requested changes
There is still a problem with the weights.

2021-03-09 13:58 UTC, dvandyk commented on python/eos/plot/plotter.py
> +                self.weights = item['data']['weights'] if 'weights' in item['data'] else None
This doesn't work either, does it? Now the weights will be set to ``None`` even if ``log_weights`` are provided.

2021-03-09 13:58 UTC, dvandyk commented on python/eos/plot/plotter.py
> +                self.weights = item['data']['weights'] if 'weights' in item['data'] else None
Ditto, see above.

2021-03-09 13:58 UTC, dvandyk commented on python/eos/plot/plotter.py
> +                self.weights = item['data']['weights'] if 'weights' in item['data'] else None
Ditto, see above.

2021-03-09 15:57 UTC, pluegh commented
Third time's the charm.

The code is very explicit (read: foolproof...) now and manually verified for all cases.

2021-03-09 17:23 UTC, dvandyk approved these changes
Thanks, that looks good!

2021-03-09 17:25 UTC, merged