[doc] Add basics fix typo in use-cases
eos/eos pull request #329
Opened 2021-06-21 22:10 UTC by SKuerten

Add basics to the online documentation

2021-06-22 18:08 UTC, dvandyk requested changes

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +.. parsed-literal::
Uhh, I did not know about this!

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +We can populate this object with a choice of kinematic variables: - We
Itemization not working!

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +the ``eos.Options`` class. In many cases, the processes have a default
``eos.Option``, not ``eos.Options``.

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +expressed through a Python exception.
``[...] if the mandatory option is not specified by you!``

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +include: - ``model``, to select a BSM model; - ``form-factors``, to
itemization!

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +     # The list is rather long; uncomment the following line by removing the leading '#'
Please remove the comment and the leading '#', since this is not a notebook.

2021-06-22 18:08 UTC, dvandyk commented on doc/basics.rst
> +Any observable can be handled just like any other Python object. For
``Any`` or ``An``?

2021-06-22 18:08 UTC, dvandyk commented on doc/use-cases.rst
> +   :width: 600
Please undo this change, whatever it is :smile:

2021-07-01 17:18 UTC, SKuerten commented
I'm not completely done yet. I messed up some rst syntax. Will fix that later

2021-07-02 11:25 UTC, SKuerten commented on doc/basics.rst
> +lengthy. Let’s have a look at something more manageable: the parameters
I think that's a misunderstanding. parameters is defined in line 40 and contains the complete lists of parameters, thus the plural. I don't think singular makes sense here?

2021-07-06 07:35 UTC, dvandyk approved these changes

2021-07-06 07:35 UTC, dvandyk commented on doc/basics.rst
> +lengthy. Let’s have a look at something more manageable: the parameters
But there is only a single parameter for the muon mass!

2021-07-06 07:35 UTC, merged