Add seed to nested sampling
eos/eos pull request #606
Opened 2023-02-28 10:20 UTC by fnovak42

As discussed in issue #573, a seed was added to the rng used by the `DynamicNestedSampler`

2023-02-28 11:11 UTC, dvandyk requested changes
This looks reasonable, thanks! However, the change should also be reflected in `eos-analysis`, where the same default value for the seed should be used as in the task.

2023-03-01 20:20 UTC, fnovak42 commented
For simplicity, I've added just the `int` option in the task and parser specifications for the seed. Technically, we could also use an array or `None`, but I'm not sure if this is practically relevant.

2023-03-02 10:55 UTC, mreboud requested changes
Have you been able to check that it works as expected? I would run 3 nested samplings: 2 with the default seed and a with another one. Then you can check that the events in the two first samplings are the same and don't match the ones in the third sampling.

2023-03-02 10:55 UTC, mreboud commented on src/scripts/eos-analysis
> +    parser_sample_nested.add_argument('-s', '--rng-seed',
Can you use the command `--use-random-seed` for consistency with the `find-mode` task?

2023-03-02 12:25 UTC, fnovak42 commented
> Have you been able to check that it works as expected? I would run 3 nested samplings: 2 with the default seed and a with another one. Then you can check that the events in the two first samplings are the same and don't match the ones in the third sampling.

All right, that sound like a better way to check it, I will try that. I just ran two samplings, one with the default seed and one with a different one.

2023-03-04 13:08 UTC, dvandyk approved these changes
Looks good now, thank you @fnovak42!

2023-03-04 13:08 UTC, merged