[form-factors] Add subtracted kkvdz2022 form factors
eos/eos pull request #611
Opened 2023-03-07 18:16 UTC by SKuerten

First try on adding the subtractions in kkvdz form factors.
ToDo:
 - [ ] Learn how to and actually assign the correct values to the subtraction constants (for now it's only copied from the a-array).
 - [ ] Add option for switching between subtracted and unsubtracted dispersion relation.
 - [ ] For now this change does nothing change in the observables since they only use the unsubtracted form factors.
 - [ ] Add test cases for the subtracted form factors.

2023-04-03 14:48 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +        _c_rho{{{ UsedParameter(p[0.0],  *this),
Hm. Can you distinguish the subtraction constants in the ``rho`` dispersion relation from those of the ``omega`` dispersion relation?

2023-04-03 14:55 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +                (a_0 + a_1 * diff_z + a_2 * power_of<2>(diff_z) ) + switch_subtracted * (c_0 + c_1 * diff_z + c_2 * power_of<2>(diff_z) + s_0 *
I think this is incorrect. IMHO, the "constant" part does not enter multiplied by the omega's Breit-Wigner.

2023-04-03 14:55 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +        return 1.0 / (1.0 - k2 / m_r_sq) * m_rho_sq / ( m_rho_sq - q2 - 1.0i * sqrt(q2) * _width_rho(q2) ) * ( (1.0 - switch_subtracted) *
Ditto.

2023-06-20 08:12 UTC, mreboud commented
I also noticed that you wrote KKVDZ with an uppercase V, it should be lowercase :)

2023-06-20 14:25 UTC, mreboud commented
Ideally it would be nice to have the options here: https://github.com/eos/eos/blob/bdab45c6861c7222e439372de4642c1eab09c654/eos/form-factors/parametric-kkvdz2022.cc#L226

But this is something I have to do throughout EOS anyway...

2023-06-26 08:34 UTC, dvandyk requested changes
I doubt that you tested this PR.

 - There is no changeset introducing the new parameters for the new subtraction parameters.
 - You do not associate new parameters with your newly-introduced ``UserParameter`` objects.
 - I think there is a sign error in the subtracted dispersion relation for both rho and omega.

2023-06-26 08:34 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +        opt_subtracted(o, "subtracted", { "off", "on"}, "off"),
Inconsistent whitespace after ``"on"``.

2023-06-26 08:34 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +        _s_0(p[0.0],  *this),
Inconsistent whitespace before ``*this``.

2023-06-26 08:34 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +        _c_subtraction{{{ UsedParameter(p[0.0],  *this),
I had no idea this worked. Why are you looking up a parameter by index. Even more so, why are you using a ``float`` as the index?

2023-06-26 08:34 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +               switch_subtracted * (q2 - s_0) / (s_0 - m_omega_sq) * omega_bw * (a_0 + a_1 * diff_z + a_2 * power_of<2>(diff_z) ) );
Please check if the sign of the new term is correct. I suspect that the factor should read ``(q2 - s_0) / (m_omega_sq - s_0)``.

2023-06-26 08:34 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +               switch_subtracted * (q2 - s_0) / (s_0 - m_rho_sq) * rho_bw * (a_0 + a_1 * diff_z + a_2 * power_of<2>(diff_z) ) );
See above.

2023-06-26 08:34 UTC, dvandyk commented on eos/form-factors/parametric-kkvdz2022.cc
> +    KKvDZ2022FormFactors::_subtraction_polynomial(const double & k2, const std::array<UsedParameter, 3> & c) const
That's a good idea, adding a new function for the subtraction polynomial.

2023-07-26 09:04 UTC, dvandyk approved these changes

2023-07-26 10:58 UTC, merged