Filter samples task
eos/eos pull request #957
Opened 2024-11-29 11:30 UTC by MJKirk

A minimum working example here -- for now, can only filter based on a set of observables from a Prediction part of an analysis file, and the resulting mask can be applied to `predict-observables`.
The mask reading and writing should almost certainly be split off into a new class in eos/data/native, I just couldn't be bothered to do it yet.
This draft PR is just to allow some discussion of the details.

In terms of defining the observables, I see three potential options:
1. Give a comma separated list on the command line, e.g. `--filter-obs=0->pipi::Arg{f_+}(q2);I=1;q2=0.5,0->pipi::Arg{f_+}(q2);I=1;q2=1`
2. Re-use the `predictions` section of the analysis file, as done here
3. Add a new `filtering-obs` section, which is essentially a copy of the predictions section
4. 
My preference would be 3., as specifying full observables via the command line as in 1. seems difficult to do in general (unless they can only refer to custom observables from the analysis file, and all the kinematics/options are fixed there -- and this case would basically become 3. anyway).
For case 3., you could also specify the mask label in the analysis file, and so the user would just need to give the name of the filter set and the posterior as an argument.

2024-12-03 09:23 UTC, dvandyk commented
Comments from today's dev meeting:
- rename task from ``filter-samples`` to ``create-mask``
- record the settings for a mask under ``masks`` (example from [the recent paper with @smeiser](https://arxiv.org/pdf/2411.09458))
```
masks:
  - name: WET1A
    description:
      - expression: '+1.0 * [[qbcu::Re[c1}]]  + 1.17 * [[qbcu::Re{c2}]] + 1.6' # valid expression observables
      - expression: '-1.0 * [[qbcu::Re[c1}]]  - 1.17 * [[qbcu::Re{c2}]] + 1.6'
      - observable: 'B_s->D_spi::BR' # physical nonsense, just illustrating the use of regular observables
```
The solution ``WET1A`` from the paper has the first two indicators positive.

2024-12-07 15:59 UTC, dvandyk commented on python/eos/analysis_file.py
> +            self._masks = []
This should probably be ``self._masks = {}``.

2024-12-17 09:38 UTC, MJKirk commented
Suggestion for the expression part: make the user give a name

2025-02-11 09:35 UTC, MJKirk commented
@smeiser wanted to be able to make masks that look like `(cond1 && cond2) || (cond3 && cond4)`. I suggest 
1) allowing the list of observables in a mask to be applied via `or` rather than just `and`
2) allowing another mask to be specified, in addition to an EOS Observable or a expression string.
Which would allow (roughly):
```yaml
masks:
  - name: mask1
    combination: and
    description:
      - name: '0->pipi::Arg{f_+}(2)'
        expression: '<<0->pipi::Arg{f_+}(q2)>>[q2=2] - 4.5'
  - name: mask2
    combination: and
    description:
      - name: 0->pipi::b3
        expression: '[[0->pipi::b_(+,1)^3@KKRvD2024]] + 0.1'
      - name: 0->pipi::b4
        expression: '[[0->pipi::b_(+,1)^4@KKRvD2024]] + 0.05'
  - name: mask3
    combination: or
    description:
      - mask: mask1
      - mask: mask2
```

2025-03-20 13:05 UTC, mreboud requested changes
Thanks @MJKirk , I left a few comments but it looks already quite good :)

2025-03-24 11:02 UTC, MJKirk commented on python/eos/analysis_file_description.py
> +#  ???????
Whoops - poorly done rebase here

2025-03-24 11:18 UTC, MJKirk commented on python/eos/analysis_file.py
> +                        eos.Observables().insert(d.name, "", eos.Unit("1"), eos.Options(), d.expression)
What do you mean by the analysis' options? The analysis as a whole doesn't have options, only a given posterior or prediction has options specified.

2025-03-24 11:30 UTC, MJKirk commented on python/eos/analysis_file.py
> +        counts = Counter()
I couldn't think of anything simpler that wouldn't effectively just be re-implementing `Counter` myself

2025-04-08 08:14 UTC, mreboud commented on python/eos/analysis_file.py
> +                        eos.Observables().insert(d.name, "", eos.Unit("1"), eos.Options(), d.expression)
Yes you are correct, sorry

2025-04-08 08:16 UTC, mreboud commented on python/eos/analysis_file.py
> +        counts = Counter()
Why not use a set and check that the size of the set is the one you expected?

2025-04-10 09:29 UTC, MJKirk commented on python/eos/analysis_file.py
> +        counts = Counter()
Because I want to know which names are repeated, not just that some are, so I can raise a more useful error message.

2025-04-22 08:08 UTC, mreboud commented on python/eos/analysis_file.py
> +        counts = Counter()
Fine, happy to use counter!

2025-04-22 14:31 UTC, merged